In [14]:
import warnings
import itertools
import numpy as np
import matplotlib.pyplot as plt
warnings.filterwarnings("ignore")
plt.style.use('fivethirtyeight')
import pandas as pd
import statsmodels.api as sm
import matplotlib
matplotlib.rcParams['axes.labelsize'] = 14
matplotlib.rcParams['xtick.labelsize'] = 12
matplotlib.rcParams['ytick.labelsize'] = 12
matplotlib.rcParams['text.color'] = 'k'

In [17]:
df = pd.read_csv("coFiltered1.csv")
df

,date,state,positive,negative,hospitalized_currently,hospitalized_cumulative,in_icu_currently,in_icu_cumulative,on_ventilator_currently,on_ventilator_cumulative,recovered,data_quality_grade,death,total_test_results
0,2020-07-24,AK,2748.0,197824.0,37.0,NaN,NaN,NaN,1.0,NaN,800.0,A,19.0,200572
1,2020-07-24,AL,76005.0,552979.0,1570.0,9157.0,NaN,1058.0,NaN,565.0,32510.0,B,1438.0,628984
2,2020-07-24,AR,37249.0,424215.0,497.0,2361.0,NaN,NaN,109.0,329.0,29827.0,A+,394.0,461464
3,2020-07-24,AS,0.0,1037.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,0.0,1037
4,2020-07-24,AZ,156301.0,680516.0,2844.0,7461.0,837.0,NaN,575.0,NaN,20171.0,A+,3142.0,836817
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8478,2020-01-26,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
8479,2020-01-25,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
8480,2020-01-24,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
8481,2020-01-23,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
8482,2020-01-22,WA,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

In [18]:
df['date'].min(), df['date'].max()

('2020-01-22', '2020-07-24')

In [27]:
df.index = pd.to_datetime(df.index, unit='s')
y = df['date'].resample('MS').mean()

DataError: No numeric types to aggregate